<div class="container-right">
<br/>
<p class="noHoverBG sidebar-top">
<a href="http://www4.clustrmaps.com/counter/maps.php?url=http://www.wareabouts.com" id="clustrMapsLink"><img src="http://www4.clustrmaps.com/counter/index2.php?url=http://www.wareabouts.com" style="border:0px; padding-left:3px;" width="175" height="96" alt="Locations of visitors to this page" title="Locations of visitors to this page" id="clustrMapsImg" />
</a>
<script type="text/javascript">
function cantload() {
img = document.getElementById("clustrMapsImg");
img.onerror = null;
img.src = "http://www2.clustrmaps.com/images/clustrmaps-back-soon.jpg";
document.getElementById("clustrMapsLink").href = "http://www2.clustrmaps.com";
}
img = document.getElementById("clustrMapsImg");
img.onerror = cantload;
</script>
</p>

<br/>

<?php 
include 'rightRandom.inc';  
//include 'recentComments.inc';  
?>

</div> <!-- end container-right div -->
