<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
        <title>wareabouts :: <?php echo $titleToInsertInHead ?></title>

        <meta http-equiv="Content-type" content="text/html; charset=iso-8859-1" />
        <meta name="author" content="Richard Ware"/>
        <meta name="copyright" content="www.wareabouts.com"/>
        <meta name="description" content=" www.wareabouts.com - <?php echo $titleToInsertInHead ?>"/>
<?php
	if (!isset($metaKeywordsInHead)) {
	   $metaKeywordsInHead="wareabouts";
	}
?>
        <meta name="keywords" content="<?php echo $metaKeywordsInHead ?>" />
        <meta name="robots" content="index,follow"/>
        <meta name="robots" content="noarchive"/>

        <link rel="shortcut icon" href="http://www.wareabouts.com/image/favicon.ico"/>

        <script type='text/javascript' src='/js/jquery.js'></script>
        <script type='text/javascript' src='/js/jquery.cookie.js'></script>
        <script type='text/javascript' src='/highslide/highslide.js'></script>
        <script type='text/javascript' src='/js/wa.js'></script>
        <script type='text/javascript' src='/js/jquery.dimensions.js'></script>
        <script type='text/javascript' src='/js/fx.shadow.js'></script>
        <script type='text/javascript' src='/jdMenu/jquery.jdMenu.js'></script>
        <script type='text/javascript' src='/jdMenu/jquery.bgiframe.js'></script>
        <script type='text/javascript' src='/js/thickbox.js'></script>
        <script type='text/javascript' src='/js/menu.js'></script>
        <script type='text/javascript' src='/js/jquery.autocomplete.js'></script>

        <link href="/css/lightwindow.css" rel="stylesheet" type="text/css" media="screen" />
        <link href="/css/style.css" rel="stylesheet" type="text/css"/>
		<link rel="alternate" type="application/rss+xml" title="RSS" href="http://www.wareabouts.com/rss.xml"/>